// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykvxksxiuvgwfrduloez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlrdnhrc3hpdXZnd2ZyZHVsb2V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTg2MTAsImV4cCI6MjA3NDE5NDYxMH0.AKEKjDncKXw4Av0zmTqfSFLe5Wl6BReylqygd9ihRxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});